defaults:
  - default@_here_
  - _self_
publisher:
  # two realsense cameras
  realsense_camera_publisher: 
    - camera_serial_number: '036422060422'
      camera_type: 'D400'  
      camera_name: 'external_camera' 
      rgb_resolution: [640, 480]
      depth_resolution: [640, 480]
      random_sample_point_num: 10000
      enable_pcd_publisher: True
      fps: 10
      decimate: 2  # (0-4) decimation_filter magnitude for point cloud
    - camera_serial_number: '135122079769'
      camera_type: 'D400'  
      camera_name: 'left_wrist_camera'
      rgb_resolution: [640, 480]
      depth_resolution: [640, 480]
      random_sample_point_num: 10000
      enable_pcd_publisher: True
      fps: 10
      decimate: 2  # (0-4) decimation_filter magnitude for point cloud