defaults:
  - default@_here_
  - _self_

vr_server_ip: &vr_server_ip "192.168.2.240"

publisher:
  # two realsense cameras
  realsense_camera_publisher: 
    - camera_serial_number: '036422060422'
      camera_type: 'D400'  
      camera_name: 'external_camera' 
      rgb_resolution: [640, 480]
      depth_resolution: [640, 480]
      random_sample_point_num: 10000
      enable_pcd_publisher: True
      fps: 10
      decimate: 2  # (0-4) decimation_filter magnitude for point cloud
    - camera_serial_number: '135122079769'
      camera_type: 'D400'  
      camera_name: 'left_wrist_camera'
      rgb_resolution: [640, 480]
      depth_resolution: [640, 480]
      random_sample_point_num: 10000
      enable_pcd_publisher: True
      fps: 10
      decimate: 2  # (0-4) decimation_filter magnitude for point cloud
      enable_streaming: False
      streaming_server_ip: *vr_server_ip
      streaming_server_port: 10004
      streaming_quality: 10 # (0-100) 0: lowest quality, smallest size, 100: highest quality, largest size
      streaming_chunk_size: 1024
      streaming_display_params_list:
        - position: [ -0.8, 0.5, 1.2 ]
          rotation: [ 0., 0., 0. ]
          scale: [ 0.01, 0.01, 0.01 ]
        - position: [ 0.8, 0.5, 1.2 ]
          rotation: [ 0., 0., 0. ]
          scale: [ 0.01, 0.01, 0.01 ]